# Generated by Django 3.0.8 on 2020-07-18 00:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Target',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('target_text', models.CharField(max_length=200)),
                ('search_date', models.DateTimeField(verbose_name='date searched')),
            ],
        ),
        migrations.CreateModel(
            name='Body',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('body_text', models.CharField(max_length=5000)),
                ('target', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='word_count.Target')),
            ],
        ),
    ]
