# Generated by Django 3.0.8 on 2020-07-19 00:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('word_count', '0001_initial'),
    ]

    operations = [
    ]
