# Generated by Django 3.0.8 on 2020-07-19 00:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('word_count', '0002_auto_20200718_1703'),
    ]

    operations = [
        migrations.AlterField(
            model_name='body',
            name='body_text',
            field=models.CharField(max_length=20000),
        ),
    ]
