# Generated by Django 3.0.8 on 2020-07-25 06:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('word_count', '0003_auto_20200718_1704'),
    ]

    operations = [
        migrations.AddField(
            model_name='target',
            name='body_text',
            field=models.CharField(default=2, max_length=20000),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name='Body',
        ),
    ]
