# Generated by Django 3.0.8 on 2020-07-28 00:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('word_count', '0005_wordlist'),
    ]

    operations = [
        migrations.AddField(
            model_name='wordlist',
            name='target',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='word_count.Target'),
        ),
    ]
